admin_email: "yourname@yourhost.com"
baseurl: ""
created_by: "GNT"
font_accent: "Cardo"
font_main: "Josefin Sans"
url: https://lightload.nauminous.net
title: "Lightload"

defaults:
  - scope:
      path: "wiki"
      type: "pages"
    values:
      layout: "wiki"