admin_email: "yourname@yourhost.com"
baseurl: ""
created_by: "GNT"
font_accent: "Cardo"
font_main: "Josefin Sans"
title: "Lightload"
defaults:
  - scope:
      path: "wiki"
      type: "wiki"
    values:
      layout: "wiki"
